### ISSUE TITLE
CTIDS arguments parsing issue

### ISSUE THREAD

**Issue by evgkrsk** [AndSk/OVZ-Backup#1]
"-i" work only when I use "-t" or specify snapshot path BEFORE "-i", i.e.:

``` shell
root@dl320eg8 ~ # ovz-backup.py -i 11020 /backup/vz/
usage: ovz-backup.py [-h] [-i CTIDS [CTIDS ...]] [-e] [-d] [-v] [-t MAILTO]
                                    snapshot_path [conf_path]
ovz-backup.py: error: argument -i/--ctids: invalid int value: '/backup/vz/'
```

but

``` shell
root@dl320eg8 ~ # ovz-backup.py /backup/vz/ -i 11020 
```

 or 

``` shell
root@dl320eg8 ~ # ovz-backup.py -i 11020 -t root /backup/vz/
```

both works fine. Issue observed in git commit fc4b7f4170575f77d72974c10f593fee14429af3

**Comment by AndSk** [comment]
This happens because of how the argparse library parses command line arguments. The -i option takes a list of arguments and the parser will give it every argument it sees until a different option is reached or it sees a double dash "--" (end of options). When using positional arguments after -i you must either place a different option between them to terminate the list, or separate options and positional arguments using a double dash. All examples uses double dash, but it could be more clearly documented.

The command should work if written like this:
`ovz-backup.py -i 11020 -- /backup/vz/`

**Comment by AndSk** [comment]
README has been updated and now gives an example for when and how you must use double dash.
